<a href="https://colab.research.google.com/github/Kavya14345/INFOSYS-SPRINGBOARD/blob/main/ASSIGNMENT-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print('hi')

hi


In [3]:
import numpy as np

In [5]:
#single dimensional array
n1=np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [6]:
#multidimensional array
n2=np.array([[1,2,3],[4,5,6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#Initializing Numpy array with zeros
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [8]:
#multidimensional array
n2=np.zeros((4,4))
n2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#initializing numpy array with same numbers
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [12]:
#initializing numpy array
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
n1=np.arange(10,40,2)
n1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [14]:
n1=np.random.randint(1,45,3)
n1

array([26, 43,  5])

In [17]:
# shape
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [18]:
#shape
n1.shape=(3,2)
n1.shape

(3, 2)

In [ ]:
#vstack()
